### ISSUE TITLE
Exception in chat adapter

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/ChatMessagesAdapter-android#19]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                                          at java.util.regex.Matcher.reset(Matcher.java:1052)
                                                                          at java.util.regex.Matcher.<init>(Matcher.java:180)
                                                                          at java.util.regex.Pattern.matcher(Pattern.java:1006)
                                                                          at com.nayapay.app.chat.messageadpater.utils.LinkUtils.extractUrls(LinkUtils.java:20)
                                                                          at com.nayapay.app.chat.messageadpater.QBMessagesAdapter.fillTextMessageHolder(QBMessagesAdapter.java:404)
                                                                          at com.nayapay.app.chat.messageadpater.QBMessagesAdapter.onBindViewMsgRightHolder(QBMessagesAdapter.java:388)
                                                                          at com.nayapay.app.chat.ui.adapter.CustomMessageAdapter.onBindViewMsgRightHolder(CustomMessageAdapter.java:65)
                                                                          at com.nayapay.app.chat.messageadpater.QBMessagesAdapter.onBindViewHolder(QBMessagesAdapter.java:269)
                                                                          at com.nayapay.app.chat.messageadpater.QBMessagesAdapter.onBindViewHolder(QBMessagesAdapter.java:59)

**Comment by RomanPronin** [comment]
@Shahjahan786, for now you can override fillTextMessageHolder() in you CustomMessageAdapter  which extends QBMessagesAdapter and add null checking:
`@Override`
    `protected void fillTextMessageHolder(TextMessageHolder holder, QBChatMessage chatMessage, int position, boolean isLeftMessage) {`
       ` if(chatMessage.getBody() == null){`
          `  chatMessage.setBody("");`
    `    }`
     `   super.fillTextMessageHolder(holder, chatMessage, position, isLeftMessage);`
    `}`
