### ISSUE TITLE
java.lang.AbstractMethodError: abstract method not implemented

### ISSUE THREAD

**Issue by kishorejethava** [QuickBlox/ChatMessagesAdapter-android#21]
Could you please help me, getting below error  
`FATAL EXCEPTION: main
                                                                         Process: com.terry.wya.development, PID: 9255
                                                                         java.lang.AbstractMethodError: abstract method not implemented
                                                                             at com.quickblox.ui.kit.chatmessage.adapter.media.video.thumbnails.VideoThumbnailModule.registerComponents(VideoThumbnailModule.java)
                                                                             at com.bumptech.glide.Glide.initializeGlide(Glide.java:236)
                                                                             at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:176)
                                                                             at com.bumptech.glide.Glide.get(Glide.java:160)
                                                                             at com.bumptech.glide.Glide.getRetriever(Glide.java:583)
                                                                             at com.bumptech.glide.Glide.with(Glide.java:609)
                                                                             at com.quickblox.ui.kit.chatmessage.adapter.QBMessagesAdapter.showImageByURL(QBMessagesAdapter.java:763)
                                                                             at com.quickblox.ui.kit.chatmessage.adapter.QBMessagesAdapter.showPhotoAttach(QBMessagesAdapter.java:728)
                                                                             at com.quickblox.ui.kit.chatmessage.adapter.QBMessagesAdapter.displayAttachment(QBMessagesAdapter.java:619)
                                                                             at com.quickblox.ui.kit.chatmessage.adapter.QBMessagesAdapter.onBindViewAttachLeftHolder(QBMessagesAdapter.java:322)
                                                                             at com.quickblox.ui.kit.chatmessage.adapter.QBMessagesAdapter.onBindViewHolder(QBMessagesAdapter.java:279)
                                                                             at com.quickblox.ui.kit.chatmessage.adapter.QBMessagesAdapter.onBindViewHolder(QBMessagesAdapter.java:58)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:570)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                             at android.view.View.layout(View.java:15092)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4645)
                                                                             at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
                                                                             at android.view.View.layout(View.java:15092)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4645)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                             at android.view.View.layout(View.java:15092)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4645)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                             at android.view.View.layout(View.java:15092)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4645)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                             at android.view.View.layout(View.java:15092)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4645)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                             at android.view.View.layout(View.java:15092)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4645)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                             at android.view.View.layout(View.java:15092)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4645)
                                                                         	at android.view.ViewRootImpl.performLayout(View`

**Comment by RomanPronin** [comment]
If the issue is still actual, could you please tell, how did you get this error? Write more info, some steps, and does this error occurs in sample?

**Comment by RomanPronin** [comment]
If the issue is still actual feel free to reopen.

**Comment by Narinc** [comment]
I got same error. When I add gradle this line -> `implementation` "com.quickblox:chat-message-adapter:$rootProject.qbChatAdapterVersion"`


`E/UncaughtException: java.lang.AbstractMethodError: abstract method "void com.bumptech.glide.module.RegistersComponents.registerComponents(android.content.Context, com.bumptech.glide.Glide, com.bumptech.glide.Registry)"
                                                                                  at com.bumptech.glide.Glide.initializeGlide(Glide.java:231)
                                                                                  at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:172)
                                                                                  at com.bumptech.glide.Glide.get(Glide.java:156)
                                                                                  at com.bumptech.glide.Glide.getRetriever(Glide.java:535)
                                                                                  at com.bumptech.glide.Glide.with(Glide.java:561)
                                                                                  at com.solidict.mobilfaktoring.ui.main.sendcheque.ChequeFacesAdapter.getView(ChequeFacesAdapter.java:116)
                                                                                  at android.widget.AbsListView.obtainView(AbsListView.java:2363)
                                                                                  at android.widget.ListView.measureHeightOfChildren(ListView.java:1326)
                                                                                  at android.widget.ListView.onMeasure(ListView.java:1233)
                                                                                  at com.solidict.mobilfaktoring.widget.NonScrollableListView.onMeasure(NonScrollableListView.java:29)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1293)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                  at android.widget.ScrollView.onMeasure(ScrollView.java:340)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1632)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:911)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                  at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                                  at android.view.View.measure(View.java:19857)
                                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:621)
04-13 18:02:56.013 4641-4641/com.solidict.mobilfaktoring E/UncaughtException:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`
