### ISSUE TITLE
QBMessagesAdapter crash 

### ISSUE THREAD

**Issue by axionnneeeel** [QuickBlox/ChatMessagesAdapter-android#23]
```
Fatal Exception: java.lang.NullPointerException
       at com.quickblox.ui.kit.chatmessage.adapter.QBMessagesAdapter.isIncoming(QBMessagesAdapter.java:595)
       at com.quickblox.ui.kit.chatmessage.adapter.QBMessagesAdapter.getItemViewType(QBMessagesAdapter.java:562)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5657)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
```

**Comment by RomanPronin** [comment]
If you get NullPointerException in isIncoming() method, you can always override it and implement your logic in your adapter subclass.
